# Jykell configuration
markdown: kramdown
paginate: 2

# Website info
name: 'Finding The Way Home'
description: "A beautiful narrative written with the world's most elegant publishing platform. The story begins here."

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title

# gems and other configs
gems: [jekyll-paginate]

#TODO: jasper: add later
#google_analytics: UA-69281367-1
#disqus: username

